### ISSUE TITLE
Unable to load Insomnia

### ISSUE THREAD

**Issue by itsmartin** [rmct/AutoReferee#167]
```
2013-09-09 13:16:48 [INFO] itsmartin_ issued server command: /ar load insomnia
2013-09-09 13:16:49 [INFO] Preparing start region for level 2 (Seed: 5912605945166048085)
2013-09-09 13:16:49 [WARNING] [AutoReferee] Task #13 for AutoReferee v2.5 generated an exception
java.lang.NullPointerException
        at org.mctourney.autoreferee.AutoRefMap.createMatch(AutoRefMap.java:201)
        at org.mctourney.autoreferee.AutoRefMap$MapLoader.run(AutoRefMap.java:632)
        at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
```

**Comment by net** [comment]
Could not reproduce on craftbukkit-1.8.8 or sportbukkit-1.8.7.
