### ISSUE TITLE
Catch ZipException and output error message if a zip file cannot be opened

### ISSUE THREAD

**Issue by itsmartin** [rmct/AutoReferee#184]
A stack trace is written to the console on ```/ar update``` if there is an error in opening the zip file. It would be better if this ZipException could be caught and a helpful error message output instead.

```
2013-09-24 12:29:23 [SEVERE] java.util.zip.ZipException: error in opening zip file
2013-09-24 12:29:23 [SEVERE] at java.util.zip.ZipFile.open(Native Method)
2013-09-24 12:29:23 [SEVERE] at java.util.zip.ZipFile.<init>(ZipFile.java:215)
2013-09-24 12:29:23 [SEVERE] at java.util.zip.ZipFile.<init>(ZipFile.java:145)
2013-09-24 12:29:23 [SEVERE] at java.util.zip.ZipFile.<init>(ZipFile.java:159)
2013-09-24 12:29:23 [SEVERE] at org.mctourney.autoreferee.AutoRefMap.getConfigFileData(AutoRefMap.java:490)
2013-09-24 12:29:23 [SEVERE] at org.mctourney.autoreferee.AutoRefMap.getMapInfo(AutoRefMap.java:515)
2013-09-24 12:29:23 [SEVERE] at org.mctourney.autoreferee.AutoRefMap.getInstalledMaps(AutoRefMap.java:481)
2013-09-24 12:29:23 [SEVERE] at org.mctourney.autoreferee.AutoRefMap$MapUpdateTask.run(AutoRefMap.java:376)
```

**Comment by net** [comment]
Assuming closed.
