### ISSUE TITLE
Exception loading map MooriseMountains

### ISSUE THREAD

**Issue by itsmartin** [rmct/AutoReferee#194]
This map seems to cause a NullPointerException when loaded. Sorry for dumping the stack trace here, I don't have time to investigate further right now.

[19:11:30] [Server thread/INFO]: itsmartin_ issued server command: /ar load moonrisemountains
[19:11:30] [Server thread/INFO]: plugins/bPermissions/world-autoref-1472856eaec
[19:11:30] [Server thread/INFO]: Preparing start region for level 6 (Seed: -4576880667734084836)
[19:11:31] [Server thread/WARN]: [AutoReferee] Task #26780500 for AutoReferee v2.6-SNAPSHOT generated an exception
java.lang.NullPointerException
        at org.mctourney.autoreferee.AutoRefMap.createMatch(AutoRefMap.java:206) ~[?:?]
        at org.mctourney.autoreferee.AutoRefMap$MapLoader.run(AutoRefMap.java:645) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[sportbukkit-1.7.9-R0.1-SNAPSHOT.jar:git-SportBukkit-1.7.2-R0.3-103-g5c5b10d]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [sportbukkit-1.7.9-R0.1-SNAPSHOT.jar:git-SportBukkit-1.7.2-R0.3-103-g5c5b10d]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:602) [sportbukkit-1.7.9-R0.1-SNAPSHOT.jar:git-SportBukkit-1.7.2-R0.3-103-g5c5b10d]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [sportbukkit-1.7.9-R0.1-SNAPSHOT.jar:git-SportBukkit-1.7.2-R0.3-103-g5c5b10d]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:559) [sportbukkit-1.7.9-R0.1-SNAPSHOT.jar:git-SportBukkit-1.7.2-R0.3-103-g5c5b10d]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:472) [sportbukkit-1.7.9-R0.1-SNAPSHOT.jar:git-SportBukkit-1.7.2-R0.3-103-g5c5b10d]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [sportbukkit-1.7.9-R0.1-SNAPSHOT.jar:git-SportBukkit-1.7.2-R0.3-103-g5c5b10d]

**Comment by net** [comment]
Could not reproduce on craftbukkit-1.8.8 or sportbukkit-1.8.7.
