### ISSUE TITLE
Map Cube Control won't load

### ISSUE THREAD

**Issue by net** [rmct/AutoReferee#209]
```
[23:03:04 INFO]: Net issued server command: /ar load cubecontrol
[23:03:06 INFO]: [AutoReferee] Setting up scoreboard for ar#Orange
[23:03:06 INFO]: [AutoReferee] Setting up scoreboard for ar#Blue
[23:03:06 ERROR]: Could not pass event WorldInitEvent to AutoReferee v2.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:279) ~[sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:968) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.mctourney.autoreferee.AutoRefMap.createMatchWorld(AutoRefMap.java:224) [AutoReferee-2.8.jar:?]
	at org.mctourney.autoreferee.AutoRefMap.createMatch(AutoRefMap.java:213) [AutoReferee-2.8.jar:?]
	at org.mctourney.autoreferee.AutoRefMap$MapLoader.run(AutoRefMap.java:660) [AutoReferee-2.8.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:696) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:351) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:645) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:555) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: No enum constant org.mctourney.autoreferee.AutoRefMatch.RespawnMode.BEDSONLY
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_60]
	at org.mctourney.autoreferee.AutoRefMatch$RespawnMode.valueOf(AutoRefMatch.java:2997) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.parseExtraGameRules(AutoRefMatch.java:1463) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.loadWorldConfiguration(AutoRefMatch.java:1377) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.loadWorldConfiguration(AutoRefMatch.java:1160) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.<init>(AutoRefMatch.java:965) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.<init>(AutoRefMatch.java:926) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.setupWorld(AutoRefMatch.java:1839) ~[?:?]
	at org.mctourney.autoreferee.listeners.WorldListener.checkLoadedWorld(WorldListener.java:48) ~[?:?]
	at org.mctourney.autoreferee.listeners.WorldListener.worldInit(WorldListener.java:40) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:277) ~[sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	... 14 more
[23:03:06 INFO]: Preparing start region for level 3 (Seed: -1451820048568930963)
[23:03:06 INFO]: [AutoReferee] Setting up scoreboard for ar#Orange
[23:03:06 INFO]: [AutoReferee] Setting up scoreboard for ar#Blue
[23:03:06 ERROR]: Could not pass event WorldLoadEvent to AutoReferee v2.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:279) ~[sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:995) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.mctourney.autoreferee.AutoRefMap.createMatchWorld(AutoRefMap.java:224) [AutoReferee-2.8.jar:?]
	at org.mctourney.autoreferee.AutoRefMap.createMatch(AutoRefMap.java:213) [AutoReferee-2.8.jar:?]
	at org.mctourney.autoreferee.AutoRefMap$MapLoader.run(AutoRefMap.java:660) [AutoReferee-2.8.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:696) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:351) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:645) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:555) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: No enum constant org.mctourney.autoreferee.AutoRefMatch.RespawnMode.BEDSONLY
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_60]
	at org.mctourney.autoreferee.AutoRefMatch$RespawnMode.valueOf(AutoRefMatch.java:2997) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.parseExtraGameRules(AutoRefMatch.java:1463) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.loadWorldConfiguration(AutoRefMatch.java:1377) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.loadWorldConfiguration(AutoRefMatch.java:1160) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.<init>(AutoRefMatch.java:965) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.<init>(AutoRefMatch.java:926) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMatch.setupWorld(AutoRefMatch.java:1839) ~[?:?]
	at org.mctourney.autoreferee.listeners.WorldListener.checkLoadedWorld(WorldListener.java:48) ~[?:?]
	at org.mctourney.autoreferee.listeners.WorldListener.worldLoad(WorldListener.java:44) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:277) ~[sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	... 14 more
[23:03:06 ERROR]: [AutoReferee] Task #5 for AutoReferee v2.8 generated an exception
java.lang.NullPointerException
	at org.mctourney.autoreferee.AutoRefMap.createMatch(AutoRefMap.java:214) ~[?:?]
	at org.mctourney.autoreferee.AutoRefMap$MapLoader.run(AutoRefMap.java:660) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:696) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:351) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:645) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:555) [sportbukkit-1.8.7-R0.1-SNAPSHOT.jar:git-Bukkit-7829f04]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Comment by net** [comment]
Closed in Cube Control 1.0.10.
